modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "vc_gliders"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
Gliders: essential for traversing terrain and preventing falls
'''
#logoFile = ""

[[dependencies.vc_gliders]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vc_gliders]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vc_gliders]]
modId = "palladiumcore"
mandatory = true
versionRange = "[1.19.2-1.2.0.0,)"
ordering = "AFTER"
side = "BOTH"