modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "vc_gliders"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
Gliders: essential for traversing terrain and preventing falls
'''
#logoFile = ""

[[dependencies.vc_gliders]]
modId = "neoforge"
mandatory = true
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vc_gliders]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vc_gliders]]
modId = "palladiumcore"
mandatory = true
versionRange = "[1.19.2-1.2.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vc_gliders]]
modId = "commonnetworking"
mandatory = true
versionRange = "[1.0.16-1.21,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "vc_gliders-common.mixins.json"